// GENERATED By migration_gen.sh

package migration

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

var createTable20240531180603 = &gormigrate.Migration{
	ID: "20240531180603",
	Migrate: func(db *gorm.DB) error {
		// TODO add migration logic
		return nil
	},
	Rollback: func(db *gorm.DB) error {
		// TODO add rollback logic
		return nil
	},
}
