// GENERATED By migration_gen.sh

package migration

import (
	"github.com/go-lang-base-app/internal/models"

	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

var initSchema20240531180603 = &gormigrate.Migration{
	ID: "20240531180603",
	Migrate: func(db *gorm.DB) error {
		return db.AutoMigrate(
			&models.User{},
		)
	},
	Rollback: func(db *gorm.DB) error {
		return db.Migrator().DropTable(&models.User{})
	},
}
