version: '3'
services:
  # web:
  #   container_name: go_lang_base_app
  #   ports:
  #     - "9090:80"
  #   image: 
  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/go_lang_base_app
    volumes:
      - .:/var/lib/postgresql/data
    
# volumes:
# networks:
