version: '3'
services:
  web:
    container_name: go_base_app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    volumes:
      - ./:/go_base_app
  postgres:
    image: postgres
    restart: always
    container_name: go_app_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: go_app_database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - db:/var/lib/postgresql/pg_data
volumes:
  cache:
    driver: local
  db:
    driver: local

