#!/bin/bash

while getopts u:a:f: flag
do
    case "${flag}" in
        f) name=${OPTARG};;
    esac
done

snake_case_name=${name// /_}
camel_case_name=$( echo "${name//_/ }" | awk 'BEGIN{OFS=""};{for(j=1;j<=NF;j++){ if(j==1){$j=tolower($j)} else {$j=toupper(substr($j,1,1)) tolower(substr($j,2)) }}}1')

id=$(date '+%Y%m%d%H%M%S')
filename=$id"_"$snake_case_name".go"
var_name=$camel_case_name$id
location="./db/migrations/"$filename

cat <<EOF >$location
// GENERATED By migration_gen.sh

package migration

import (
	"github.com/go-gormigrate/gormigrate/v2"
	"gorm.io/gorm"
)

var $var_name = &gormigrate.Migration{
	ID: "$id",
	Migrate: func(db *gorm.DB) error {
		// TODO add migration logic
		return nil
	},
	Rollback: func(db *gorm.DB) error {
		// TODO add rollback logic
		return nil
	},
}
EOF

echo "migration id: $id"
echo "filename: $filename"
echo "location: $location"
